name = "aliyun-cdn-certbot-worker"
main = "main.js"
compatibility_date = "2024-04-06"

[triggers]
crons = ["0 0 * * *"]  # 每天午夜运行一次

[dependencies]
acme-client = "^4.2.5"

[vars]
# 阿里云配置
ALIYUN_ACCESS_KEY_ID = ""  # 替换为您的阿里云 Access Key ID
ALIYUN_ACCESS_KEY_SECRET = ""  # 替换为您的阿里云 Access Key Secret
ALIYUN_DOMAIN_NAME = ""  # 替换为您的域名
ALIYUN_REGION = "cn-hangzhou"
ALIYUN_ENDPOINT = "https://cdn.console.aliyun.com/data/api.json"
ALIYUN_CERT_NAME = "auto-renewed-cert"

# Let's Encrypt 配置
LE_EMAIL = ""  # 替换为您的邮箱
LE_DIRECTORY_URL = "https://acme-v02.api.letsencrypt.org/directory"  # 生产环境
# LE_DIRECTORY_URL = "https://acme-staging-v02.api.letsencrypt.org/directory"  # 测试环境